; Capture Rate (difficulty) constants. higher = easier

CAP_EASY_MIN	EQU 255
CAP_EASY		EQU 225 
CAP_EASY_PLUS	EQU 190

CAP_MID_MIN		EQU 180 
CAP_MID			EQU 120
CAP_MID_PLUS	EQU 90 

CAP_HARD_MIN	EQU 70 
CAP_HARD		EQU 45  
CAP_HARD_PLUS	EQU 15

CAP_LEGENDARY	EQU 7

CAP_IMPOSSIBLE	EQU 0